### ISSUE TITLE
Segmentation faults (Histogram class)

### ISSUE THREAD

**Issue by samanemami** [zzd1992/GBDTMO#12]
I opened a new issue regarding the segmentation error, as the #2 issue has already closed, but the problem of course doesn't come from the `num_threads` or the `numba` library, as I tried all versions of `numba` and `llvmlite` and different values for `num_threads`.
As I thought it could be a critical issue, I explored more this problem.
Moreover, each Linux System has a different treatment to this problem by having different hardware configurations.

One possible option that produces this issue would be multi-`processing` I think.

**Comment by samanemami** [comment]
If we ignore the `numba`, the problem is still there

**Comment by samanemami** [comment]
After running a 2-fold randomized search with one value in the grid, I received this error;
```logs
TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGABRT(-6)}
```
Or even the grid search. For all tunning methods or even fit the model with a large dataset, the situation is the same.

**Comment by samanemami** [comment]
> Update
After trying different scenarios, I found that it does not necessarily come from the `numba` or `pool`.
@zzd1992 Any suggestion?

**Comment by samanemami** [comment]
This gist is an example of my implementation to tune the hyperparameters of the `GBDT-MO `model.
The dataset here is `Sensit`, but you can replace it with `poker`, or `CIFAR`.
<script src="https://gist.github.com/samanemami/f81c81b95273d261c8e103117df4d1c6.js"></script>

**Comment by samanemami** [comment]
@zzd1992 Could you please check the encoding method of categorical features?

**Comment by zzd1992** [comment]
I suggest you check whether there are missing values or nan values in the dataset.
And please check whether the number of classes equals to `out_dim`.
