### ISSUE TITLE
Can't run your exmaple code in my machine.

### ISSUE THREAD

**Issue by clouddesert** [zzd1992/GBDTMO#14]
First thank you for developping this method. 
After I followed your installation steps, I tried to run your exmaple code, i.e. test.py.
I use the following command in my linux environment.
```
bash make.sh

pip install .

cd exmaple/

python test.py
```
Then the console will generate an error "Segmentation fault (core dumped)"
I tried it on several Linux machines, and the error occurred as above.

And when I used VScode for single-step debugging on a visual linux, I found that the running of the program would automatically stop when it was run to the first C library call(line 168 of gbdtmo.py), and no error was reported.

I think it may be a problem with the python environment, but I've tried many times and can't solve it. If you have encountered the above, please let me know the solution, I would be very grateful.

**Comment by zzd1992** [comment]
Could you report your environment?
And please don't use anaconda.

**Comment by zzd1992** [comment]
It looks like caused by `numpy.ctypeslib` which provides a interface to c++ code.
In my environment, `numpy<=1.19` works well.
But I have not checked whether it works for `numpy>=1.20`.

**Comment by clouddesert** [comment]
Thank you for answering, now I have successfully run the exmaple code.
I used native python without conda, then degraded my numpy to 1.19 and upgraded numba to the latest version(0.54.1), and it works fine.
