### ISSUE TITLE
你好，有个关于GBDT-MO的问题请教一下

### ISSUE THREAD

**Issue by dagongge** [zzd1992/GBDTMO#25]
在你的GBDT-MO论文中所描述的GBDT的目标函数加入了正则化项，而且在对损失函数进行近似估计的时候采用的是泰勒展开到二阶导，这与xgboost算法的目标函数以及泰勒展开原则完全一样，并且我们所熟知的GBDT的目标函数是没有正则化项的并且泰勒展开到一阶导，所以是否这里有一些问题，应该是xgboost-MO而不是GBDT-MO因为主体是xgboost？
希望能帮我解答一下这个问题，谢谢！

**Comment by zzd1992** [comment]
感激对这个项目的关注。
1. 同样是二阶泰勒展开，GBDT-MO和XGBoost有一些区别。XGBoost是单变量，GBDT-MO是多变量。多变量二阶展开涉及到hessian矩阵，开销比较大，所以只用对角hessian矩阵作近似。虽然对角近似后最终形式一致，还是要注意推导过程中的近似处理。实际上，我也做过用exact hessian的实验。
2. 除了XGBoost，LightGBM也使用二阶泰勒展开。我这个工作主要是把GBDT推广到多变量，并展示了其优势：更快的速度/更高的准确。这个项目的基础实现实际上更接近LightGBM（直方图加速）。
3. “我们所熟知的GBDT的目标函数是没有正则化项的并且泰勒展开到一阶导”。我不觉得GBDT一定是一阶导，这种说法只是教科书上的一种习惯而已。从我个人的角度，XGBoost是GBDT的一个特例，即GBDT框架下的一种具体实现。GBDT是一类算法的统称。

所以我觉得GBDT-MO这个名字更有一般性。

**Comment by dagongge** [comment]
感谢作者回答，很有帮助！
